[env]
TERM = "alacritty"

[font]
size = 14

[window]
decorations = "full"
startup_mode = "Maximized"

[window.padding]
x = 20

[cursor.style]
shape = "Underline"
blinking = "On"

[colors.primary]
background = '#17191d'
foreground = '#abb2bf'

# Normal colors
[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

# Bright colors
[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'
